# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('poll', models.CharField(max_length=400)),
                ('created_by', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
