# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voto', '0002_auto_20170802_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voto.Escolha')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voto.Votacao')),
            ],
        ),
        migrations.DeleteModel(
            name='poll',
        ),
        migrations.DeleteModel(
            name='PollItem',
        ),
        migrations.AddField(
            model_name='escolha',
            name='votacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voto.Votacao'),
        ),
    ]
