# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0003_auto_20170803_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
