# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0004_auto_20170803_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
